# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy entire solution into container
COPY ../ ./

# Restore + publish
RUN dotnet restore BirthdayReminder/BirthdayReminder.csproj
RUN dotnet publish BirthdayReminder/BirthdayReminder.csproj -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "BirthdayReminder.dll"]